import type { Config } from 'tailwindcss';
import typography from '@tailwindcss/typography';

const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#503c74',
        'on-surface': '#e2e2e2',
        'inverse-on-surface': '#303030',
        'secondary-fixed': '#eaddff',
        'on-secondary-container': '#c2b0e5',
        'tertiary-fixed-dim': '#d4bbfd',
        'surface-container-highest': '#353535',
        tertiary: '#d4bbfd',
        'inverse-primary': '#65587d',
        surface: '#131313',
        'surface-bright': '#393939',
        'on-secondary-fixed': '#21133e',
        'on-error-container': '#ffdad6',
        'tertiary-fixed': '#ebdcff',
        'on-tertiary': '#39255c',
        'secondary-fixed-dim': '#d0bef3',
        'on-primary-container': '#897ba2',
        'surface-container': '#1f1f1f',
        'surface-container-high': '#2a2a2a',
        'inverse-surface': '#e2e2e2',
        'surface-dim': '#131313',
        outline: '#948f98',
        'primary-fixed-dim': '#cfbfea',
        'outline-variant': '#49454d',
        'surface-container-low': '#1b1b1b',
        'on-tertiary-container': '#8d77b3',
        'on-secondary-fixed-variant': '#4d3f6c',
        'primary-fixed': '#eaddff',
        'surface-tint': '#cfbfea',
        'secondary-container': '#50416e',
        'on-error': '#690005',
        'on-secondary': '#372954',
        'surface-container-lowest': '#0e0e0e',
        'on-tertiary-fixed': '#240e46',
        'on-background': '#e2e2e2',
        'error-container': '#93000a',
        'on-surface-variant': '#cbc4ce',
        'on-primary-fixed': '#201536',
        'surface-variant': '#353535',
        'on-primary-fixed-variant': '#4d4164',
        secondary: '#d0bef3',
        'tertiary-container': '#200a43',
        background: '#131313',
        error: '#ffb4ab',
        primary: '#cfbfea',
        'primary-container': '#1d1233',
        'on-primary': '#362a4d',
      },
      borderRadius: {
        none: '0',
        DEFAULT: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        '3xl': '0px',
        full: '9999px',
      },
      fontFamily: {
        headline: ['var(--font-headline)', 'Newsreader', 'serif'],
        body: ['var(--font-body)', 'Montserrat', 'sans-serif'],
        label: ['var(--font-label)', 'Manrope', 'sans-serif'],
      },
      animation: {
        marquee: 'marquee 30s linear infinite',
        'marquee-fast': 'marquee 20s linear infinite',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
    },
  },
  plugins: [typography],
};

export default config;
